### ISSUE TITLE
Plz help sorry for newbie question

### ISSUE THREAD

**Issue by blazingdevil44** [praharshjain/Vudit#4] opened 2020-07-21 06:32 UTC
How can i open a folder directly for example i have a folder path and i want to open it directly and set it as default folder so that i can explore anything in folder e.g opening subfolder in folder or opeining files going back to deafult folder but id i press back from default folder i go back to app

Example i have MyApp Files Folder Which i want to open directly

inside there are 2 folder folder one and folder two 

if i tap folder one i go inside it explore it etc when i press back i go back to myApp files folder but if press back again fileviewr exists and go back to App

**Comment by praharshjain** [comment] 2023-02-02 06:32
Duplicate of https://github.com/praharshjain/Vudit/issues/6

**Closed as completed by praharshjain** 2023-02-02 06:32 UTC
Labels: duplicate
